[delta "kanagawa-paper-ink-strong-diff"]
    ; Text and background colors
    minus-style                   = syntax "#442C31"
    minus-emph-style              = bold "#FF5D62" "#6B333E"
    plus-style                    = syntax "#283C2E"
    plus-emph-style               = bold "#98BB6C" "#3B5842"
    zero-style                    = syntax

    ; Hunk headers & decorations
    hunk-header-style             = syntax bold
    hunk-header-decoration-style = "#2A2A37" box
    file-style                    = "#c4b28a" bold
    file-decoration-style         = "#727169" overline

    ; ; Line numbers column
    ; line-numbers                = true
    ; line-numbers-minus-style    = "#C34043"
    ; line-numbers-plus-style     = "#76946A"
    ; line-numbers-left-style     = "#54546D"
    ; line-numbers-right-style    = "#54546D"
    ; line-numbers-zero-style     = "#54546D"

    file-added-label              = [+]
    file-copied-label             = [C]
    file-modified-label           = [~]
    file-removed-label            = [-]
    file-renamed-label            = [R]

[delta "kanagawa-paper-ink"]
    dark = true

    ; Text and background colors
    minus-style                   = syntax "#3F2229"
    minus-emph-style              = syntax bold "#6B2D38"
    plus-style                    = syntax "#223526"
    plus-emph-style               = syntax bold "#34523B"
    zero-style                    = syntax

    ; Hunk header & decorations
    hunk-header-style             = syntax bold
    hunk-header-decoration-style  = "#2A2A37" box
    file-style                    = "#c4b28a" bold
    file-decoration-style         = none

    ; ; Line numbers column
    ; line-numbers                = true
    ; line-numbers-minus-style    = "#C34043"
    ; line-numbers-plus-style     = "#76946A"
    ; line-numbers-left-style     = "#54546D"
    ; line-numbers-right-style    = "#54546D"
    ; line-numbers-zero-style     = "#54546D"
