[delta "kanagawa-paper-ink"]
    dark = true

    ; Text and background colors
    minus-style                   = syntax "#452f33"
    minus-emph-style              = bold "#FF5D62" "#6e373b"
    plus-style                    = syntax "#2c3732"
    plus-emph-style               = bold "#98BB6C" "#43533c"
    zero-style                    = syntax

    ; Hunk header & decorations
    hunk-header-style             = syntax bold
    hunk-header-decoration-style  = "#2A2A37" box
    file-style                    = "#c4b28a" bold
    file-decoration-style         = none
    file-added-label              = [+]
    file-copied-label             = [C]
    file-modified-label           = [~]
    file-removed-label            = [-]
    file-renamed-label            = [R]


    ; ; Line numbers column
    ; line-numbers                = true
    ; line-numbers-minus-style    = "#C34043"
    ; line-numbers-plus-style     = "#76946A"
    ; line-numbers-left-style     = "#54546D"
    ; line-numbers-right-style    = "#54546D"
    ; line-numbers-zero-style     = "#54546D"

[delta "kanagawa-paper-ink-brighter"]
    ; Text and background colors
    minus-style                   = syntax "#442C31"
    minus-emph-style              = bold "#FF5D62" "#6B333E"
    plus-style                    = syntax "#283C2E"
    plus-emph-style               = bold "#98BB6C" "#3B5842"
    zero-style                    = syntax

    ; Hunk headers & decorations
    hunk-header-style             = syntax bold
    hunk-header-decoration-style = "#2A2A37" box
    file-style                    = "#c4b28a" bold
    file-decoration-style         = "#727169" overline
    file-added-label              = [+]
    file-copied-label             = [C]
    file-modified-label           = [~]
    file-removed-label            = [-]
    file-renamed-label            = [R]

    ; ; Line numbers column
    ; line-numbers                = true
    ; line-numbers-minus-style    = "#C34043"
    ; line-numbers-plus-style     = "#76946A"
    ; line-numbers-left-style     = "#54546D"
    ; line-numbers-right-style    = "#54546D"
    ; line-numbers-zero-style     = "#54546D"
