
[[Snippets]]
  Description = "Git: see which commits included modifications to the file in question"
  Output = ""
  Tag = []
  command = "git log -- <path_to_file>"

[[Snippets]]
  Description = "Git: show all changes made in a particular commit"
  Output = ""
  Tag = []
  command = "git show <commit_hash> --stat"

[[Snippets]]
  Description = "Git: add tracked files to index (exclude untracked files)"
  Output = ""
  Tag = []
  command = "git add -u"

[[Snippets]]
  Description = "cURL: PUT"
  Output = ""
  Tag = []
  command = "curl -X PUT \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\"id\": 1, \"name\": \"Updated Resource Name\"}' \\\n  http://localhost:3000/api/resources/1"

[[Snippets]]
  Description = "JUnit: see html report of test suite from proj root"
  Output = ""
  Tag = []
  command = "xdg-open build/reports/tests/test/index.html"

[[Snippets]]
  Description = "Mise: install and set a tool version globally"
  Output = ""
  Tag = ["mise", "install"]
  command = "mise use -g <tool>@<version>"

[[Snippets]]
  Description = "Mise: Install and set an NPM package globally"
  Output = ""
  Tag = ["mise", "npm", "global"]
  command = "mise use -g npm:<package_name>@<version>"

[[Snippets]]
  Description = "Mise: execute a specific tool version once without installing/activating"
  Output = ""
  Tag = ["mise", "exec"]
  command = "mise exec <tool>@<version> -- <command>"

[[Snippets]]
  Description = "Mise: uninstall a tool and all its versions"
  Output = ""
  Tag = ["mise", "uninstall"]
  command = "mise uninstall -a <tool>"

[[Snippets]]
  Description = "Mise: Open the global configuration file for editing"
  Output = ""
  Tag = ["mise", "config"]
  command = "mise config edit --global"

[[Snippets]]
  Description = "Clang-format: apply to whole codebase"
  Output = ""
  Tag = []
  command = "find . -iname '*.h' -o -iname '*.cpp' | xargs clang-format -i"

[[Snippets]]
  Description = "Diff: create patch file"
  Output = ""
  Tag = []
  command = "diff -urN <original_dir> <new_dir> > changes.patch"

[[Snippets]]
  Description = "Diff: apply patch file"
  Output = ""
  Tag = []
  command = "patch --dry-run -p1 < ../changes.patch"

[[Snippets]]
  Description = "Diff: undo patch file"
  Output = ""
  Tag = []
  command = "patch -R -p1 < ../changes.patch"

[[Snippets]]
  Description = "JSON: check syntax"
  Output = ""
  Tag = []
  command = "python -m json.tool keymap.json"
